// pdfs/endsinai.asy
// Draw a succession of tapes for a Finite State machine computation
// This is generated by computing/bin/fsm/fsm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// Set LaTeX defaults
import settexpreamble;
settexpreamble();
// Asy defaults
import jh;
import tape;

unitsize(1pt);

tape_output_withend("endsinai000","abba",0,"$\state{0}$");
tape_output_withend("endsinai001","bba",0,"$\state{1}$");
tape_output_withend("endsinai002","ba",0,"$\state{2}$");
tape_output_withend("endsinai003","a",0,"$\state{2}$");
tape_output_withend("endsinai004","",0,"$\state{1}$");

