// pdfs/endsinaiii.asy
// Draw a succession of tapes for a Finite State machine computation
// This is generated by computing/bin/fsm/fsm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// Set LaTeX defaults
import settexpreamble;
settexpreamble();
// Asy defaults
import jh;
import tape;

unitsize(1pt);

tape_output_withend("endsinaiii000","bbaabbaa",0,"$\state{0}$");
tape_output_withend("endsinaiii001","baabbaa",0,"$\state{0}$");
tape_output_withend("endsinaiii002","aabbaa",0,"$\state{0}$");
tape_output_withend("endsinaiii003","abbaa",0,"$\state{1}$");
tape_output_withend("endsinaiii004","bbaa",0,"$\state{1}$");
tape_output_withend("endsinaiii005","baa",0,"$\state{2}$");
tape_output_withend("endsinaiii006","aa",0,"$\state{2}$");
tape_output_withend("endsinaiii007","a",0,"$\state{1}$");
tape_output_withend("endsinaiii008","",0,"$\state{1}$");

