// pdfs/endsinaii.asy
// Draw a succession of tapes for a Finite State machine computation
// This is generated by computing/bin/fsm/fsm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// Set LaTeX defaults
import settexpreamble;
settexpreamble();
// Asy defaults
import jh;
import tape;

unitsize(1pt);

tape_output_withend("endsinaii000","bab",0,"$\state{0}$");
tape_output_withend("endsinaii001","ab",0,"$\state{0}$");
tape_output_withend("endsinaii002","b",0,"$\state{1}$");
tape_output_withend("endsinaii003","",0,"$\state{2}$");

