// pdfs/modfour.asy
// Draw a succession of tapes for a Finite State machine computation
// This is generated by computing/bin/fsm/fsm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// Set LaTeX defaults
import settexpreamble;
settexpreamble();
// Asy defaults
import jhnode;
import tape;

unitsize(1pt);

tape_output_withend("modfour000","10110",0,"$\state{0}$");
tape_output_withend("modfour001","0110",0,"$\state{1}$");
tape_output_withend("modfour002","110",0,"$\state{1}$");
tape_output_withend("modfour003","10",0,"$\state{2}$");
tape_output_withend("modfour004","0",0,"$\state{3}$");
tape_output_withend("modfour005","",0,"$\state{3}$");

