// pdfs/add.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("add000"," 11 111",1,"$\state{0}$");
tape_output("add001"," 11 111",2,"$\state{0}$");
tape_output("add002"," 11 111",3,"$\state{0}$");
tape_output("add003"," 11 111",3,"$\state{1}$");
tape_output("add004"," 111111",3,"$\state{1}$");
tape_output("add005"," 111111",3,"$\state{2}$");
tape_output("add006"," 111111",2,"$\state{2}$");
tape_output("add007"," 111111",1,"$\state{2}$");
tape_output("add008"," 111111",0,"$\state{2}$");
tape_output("add009"," 111111",0,"$\state{3}$");
tape_output("add010"," 111111",1,"$\state{3}$");
tape_output("add011","  11111",1,"$\state{4}$");
tape_output("add012","  11111",2,"$\state{5}$");

