// pdfs/addany.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// Bring in tape commands
import tape;

unitsize(1pt);

tape_output("addany000"," 11,1,11 ",1,"$\state{0}$");
tape_output("addany001"," 11,1,11 ",2,"$\state{0}$");
tape_output("addany002"," 11,1,11 ",3,"$\state{0}$");
tape_output("addany003"," 1111,11 ",3,"$\state{1}$");
tape_output("addany004"," 1111,11 ",2,"$\state{1}$");
tape_output("addany005"," 1111,11 ",1,"$\state{1}$");
tape_output("addany006"," 1111,11 ",0,"$\state{1}$");
tape_output("addany007"," 1111,11 ",1,"$\state{2}$");
tape_output("addany008","  111,11 ",1,"$\state{2}$");
tape_output("addany009","  111,11 ",2,"$\state{0}$");
tape_output("addany010","  111,11 ",3,"$\state{0}$");
tape_output("addany011","  111,11 ",4,"$\state{0}$");
tape_output("addany012","  111,11 ",5,"$\state{0}$");
tape_output("addany013","  111111 ",5,"$\state{1}$");
tape_output("addany014","  111111 ",4,"$\state{1}$");
tape_output("addany015","  111111 ",3,"$\state{1}$");
tape_output("addany016","  111111 ",2,"$\state{1}$");
tape_output("addany017","  111111 ",1,"$\state{1}$");
tape_output("addany018","  111111 ",2,"$\state{2}$");
tape_output("addany019","   11111 ",2,"$\state{2}$");
tape_output("addany020","   11111 ",3,"$\state{0}$");
tape_output("addany021","   11111 ",4,"$\state{0}$");
tape_output("addany022","   11111 ",5,"$\state{0}$");
tape_output("addany023","   11111 ",6,"$\state{0}$");
tape_output("addany024","   11111 ",7,"$\state{0}$");
tape_output("addany025","   11111 ",8,"$\state{0}$");
tape_output("addany026","   11111 ",7,"$\state{10}$");
tape_output("addany027","   11111 ",6,"$\state{10}$");
tape_output("addany028","   11111 ",5,"$\state{10}$");
tape_output("addany029","   11111 ",4,"$\state{10}$");
tape_output("addany030","   11111 ",3,"$\state{10}$");
tape_output("addany031","   11111 ",2,"$\state{10}$");
tape_output("addany032","   11111 ",3,"$\state{100}$");

