// pdfs/addonetwo.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// Bring in tape commands
import tape;

unitsize(1pt);

tape_output("addonetwo000"," 1 11",1,"$\state{0}$");
tape_output("addonetwo001"," 1 11",2,"$\state{0}$");
tape_output("addonetwo002"," 1 11",2,"$\state{1}$");
tape_output("addonetwo003"," 1111",2,"$\state{1}$");
tape_output("addonetwo004"," 1111",2,"$\state{2}$");
tape_output("addonetwo005"," 1111",1,"$\state{2}$");
tape_output("addonetwo006"," 1111",0,"$\state{2}$");
tape_output("addonetwo007"," 1111",0,"$\state{3}$");
tape_output("addonetwo008"," 1111",1,"$\state{3}$");
tape_output("addonetwo009","  111",1,"$\state{4}$");
tape_output("addonetwo010","  111",2,"$\state{5}$");

