// pdfs/addtwotwo.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("addtwotwo000"," 11 11",1,"$\state{0}$");
tape_output("addtwotwo001"," 11 11",2,"$\state{0}$");
tape_output("addtwotwo002"," 11 11",3,"$\state{0}$");
tape_output("addtwotwo003"," 11 11",3,"$\state{1}$");
tape_output("addtwotwo004"," 11111",3,"$\state{1}$");
tape_output("addtwotwo005"," 11111",3,"$\state{2}$");
tape_output("addtwotwo006"," 11111",2,"$\state{2}$");
tape_output("addtwotwo007"," 11111",1,"$\state{2}$");
tape_output("addtwotwo008"," 11111",0,"$\state{2}$");
tape_output("addtwotwo009"," 11111",0,"$\state{3}$");
tape_output("addtwotwo010"," 11111",1,"$\state{3}$");
tape_output("addtwotwo011","  1111",1,"$\state{4}$");
tape_output("addtwotwo012","  1111",2,"$\state{5}$");

