// pdfs/addthree_zero.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("addthree_zero000","    ",1,"$\state{0}$");
tape_output("addthree_zero001","    ",1,"$\state{1}$");
tape_output("addthree_zero002"," 1  ",1,"$\state{1}$");
tape_output("addthree_zero003"," 1  ",2,"$\state{2}$");
tape_output("addthree_zero004"," 11 ",2,"$\state{2}$");
tape_output("addthree_zero005"," 11 ",3,"$\state{3}$");
tape_output("addthree_zero006"," 111",3,"$\state{3}$");
tape_output("addthree_zero007"," 111",3,"$\state{4}$");
tape_output("addthree_zero008"," 111",2,"$\state{4}$");
tape_output("addthree_zero009"," 111",1,"$\state{4}$");
tape_output("addthree_zero010"," 111",0,"$\state{4}$");
tape_output("addthree_zero011"," 111",1,"$\state{5}$");

