// pdfs/addthree_four.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("addthree_four000"," 1111   ",1,"$\state{0}$");
tape_output("addthree_four001"," 1111   ",2,"$\state{0}$");
tape_output("addthree_four002"," 1111   ",3,"$\state{0}$");
tape_output("addthree_four003"," 1111   ",4,"$\state{0}$");
tape_output("addthree_four004"," 1111   ",5,"$\state{0}$");
tape_output("addthree_four005"," 1111   ",5,"$\state{1}$");
tape_output("addthree_four006"," 11111  ",5,"$\state{1}$");
tape_output("addthree_four007"," 11111  ",6,"$\state{2}$");
tape_output("addthree_four008"," 111111 ",6,"$\state{2}$");
tape_output("addthree_four009"," 111111 ",7,"$\state{3}$");
tape_output("addthree_four010"," 1111111",7,"$\state{3}$");
tape_output("addthree_four011"," 1111111",7,"$\state{4}$");
tape_output("addthree_four012"," 1111111",6,"$\state{4}$");
tape_output("addthree_four013"," 1111111",5,"$\state{4}$");
tape_output("addthree_four014"," 1111111",4,"$\state{4}$");
tape_output("addthree_four015"," 1111111",3,"$\state{4}$");
tape_output("addthree_four016"," 1111111",2,"$\state{4}$");
tape_output("addthree_four017"," 1111111",1,"$\state{4}$");
tape_output("addthree_four018"," 1111111",0,"$\state{4}$");
tape_output("addthree_four019"," 1111111",1,"$\state{5}$");

