// pdfs/addzerozero.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("addzerozero000","   ",1,"$\state{0}$");
tape_output("addzerozero001","   ",1,"$\state{1}$");
tape_output("addzerozero002"," 1 ",1,"$\state{1}$");
tape_output("addzerozero003"," 1 ",1,"$\state{2}$");
tape_output("addzerozero004"," 1 ",0,"$\state{2}$");
tape_output("addzerozero005"," 1 ",0,"$\state{3}$");
tape_output("addzerozero006"," 1 ",1,"$\state{3}$");
tape_output("addzerozero007","   ",1,"$\state{4}$");
tape_output("addzerozero008","   ",2,"$\state{5}$");

