// pdfs/addzerotwo.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("addzerotwo000","  11",1,"$\state{0}$");
tape_output("addzerotwo001","  11",1,"$\state{1}$");
tape_output("addzerotwo002"," 111",1,"$\state{1}$");
tape_output("addzerotwo003"," 111",1,"$\state{2}$");
tape_output("addzerotwo004"," 111",0,"$\state{2}$");
tape_output("addzerotwo005"," 111",0,"$\state{3}$");
tape_output("addzerotwo006"," 111",1,"$\state{3}$");
tape_output("addzerotwo007","  11",1,"$\state{4}$");
tape_output("addzerotwo008","  11",2,"$\state{5}$");

