// pdfs/append01.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("append01000"," 11  ",1,"$\state{0}$");
tape_output("append01001"," 11  ",2,"$\state{0}$");
tape_output("append01002"," 11  ",3,"$\state{0}$");
tape_output("append01003"," 110 ",3,"$\state{1}$");
tape_output("append01004"," 110 ",4,"$\state{1}$");
tape_output("append01005"," 1101",4,"$\state{2}$");
tape_output("append01006"," 1101",3,"$\state{2}$");
tape_output("append01007"," 1101",2,"$\state{2}$");
tape_output("append01008"," 1101",1,"$\state{2}$");
tape_output("append01009"," 1101",0,"$\state{2}$");
tape_output("append01010"," 1101",1,"$\state{3}$");

