// pdfs/bitwisenot.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("bitwisenot000"," 0110",1,"$\state{0}$");
tape_output("bitwisenot001"," 1110",1,"$\state{1}$");
tape_output("bitwisenot002"," 1110",2,"$\state{2}$");
tape_output("bitwisenot003"," 1010",2,"$\state{3}$");
tape_output("bitwisenot004"," 1010",3,"$\state{4}$");
tape_output("bitwisenot005"," 1000",3,"$\state{5}$");
tape_output("bitwisenot006"," 1000",4,"$\state{6}$");
tape_output("bitwisenot007"," 1001",4,"$\state{7}$");
tape_output("bitwisenot008"," 1001",3,"$\state{7}$");
tape_output("bitwisenot009"," 1001",2,"$\state{7}$");
tape_output("bitwisenot010"," 1001",1,"$\state{7}$");
tape_output("bitwisenot011"," 1001",0,"$\state{7}$");
tape_output("bitwisenot012"," 1001",1,"$\state{8}$");

