// pdfs/blankones.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("blankones000","11 ",0,"$\state{0}$");
tape_output("blankones001"," 1 ",0,"$\state{1}$");
tape_output("blankones002"," 1 ",1,"$\state{0}$");
tape_output("blankones003","   ",1,"$\state{1}$");
tape_output("blankones004","   ",2,"$\state{0}$");
tape_output("blankones005","   ",2,"$\state{2}$");

