// pdfs/constantthree.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("constantthree000","11   ",0,"$\state{0}$");
tape_output("constantthree001"," 1   ",0,"$\state{1}$");
tape_output("constantthree002"," 1   ",1,"$\state{0}$");
tape_output("constantthree003","     ",1,"$\state{1}$");
tape_output("constantthree004","     ",2,"$\state{0}$");
tape_output("constantthree005","     ",2,"$\state{2}$");
tape_output("constantthree006","  1  ",2,"$\state{2}$");
tape_output("constantthree007","  1  ",3,"$\state{3}$");
tape_output("constantthree008","  11 ",3,"$\state{3}$");
tape_output("constantthree009","  11 ",4,"$\state{4}$");
tape_output("constantthree010","  111",4,"$\state{4}$");
tape_output("constantthree011","  111",4,"$\state{5}$");
tape_output("constantthree012","  111",3,"$\state{6}$");
tape_output("constantthree013","  111",2,"$\state{7}$");

