// pdfs/doubler.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("doubler000","11     ",0,"$\state{0}$");
tape_output("doubler001","B1     ",0,"$\state{1}$");
tape_output("doubler002","B1     ",1,"$\state{2}$");
tape_output("doubler003","B1B    ",2,"$\state{2}$");
tape_output("doubler004","B1BB   ",3,"$\state{3}$");
tape_output("doubler005","B1B1   ",3,"$\state{4}$");
tape_output("doubler006","B1B1B  ",4,"$\state{5}$");
tape_output("doubler007","B1B11  ",4,"$\state{6}$");
tape_output("doubler008","B1B11  ",3,"$\state{6}$");
tape_output("doubler009","B1B11  ",2,"$\state{6}$");
tape_output("doubler010","B1B11  ",1,"$\state{7}$");
tape_output("doubler011","B1B11  ",0,"$\state{7}$");
tape_output("doubler012","B1B11  ",1,"$\state{8}$");
tape_output("doubler013","B1B11  ",1,"$\state{0}$");
tape_output("doubler014","BBB11  ",1,"$\state{1}$");
tape_output("doubler015","BBB11  ",2,"$\state{2}$");
tape_output("doubler016","BBB11  ",3,"$\state{3}$");
tape_output("doubler017","BBB11  ",4,"$\state{3}$");
tape_output("doubler018","BBB11B ",5,"$\state{3}$");
tape_output("doubler019","BBB111 ",5,"$\state{4}$");
tape_output("doubler020","BBB111B",6,"$\state{5}$");
tape_output("doubler021","BBB1111",6,"$\state{6}$");
tape_output("doubler022","BBB1111",5,"$\state{6}$");
tape_output("doubler023","BBB1111",4,"$\state{6}$");
tape_output("doubler024","BBB1111",3,"$\state{6}$");
tape_output("doubler025","BBB1111",2,"$\state{6}$");
tape_output("doubler026","BBB1111",1,"$\state{7}$");
tape_output("doubler027","BBB1111",2,"$\state{8}$");
tape_output("doubler028","BBB1111",3,"$\state{9}$");

