// pdfs/doublerbinary.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("doublerbinary000"," 110 ",1,"$\state{0}$");
tape_output("doublerbinary001"," 110 ",2,"$\state{1}$");
tape_output("doublerbinary002"," 110 ",3,"$\state{1}$");
tape_output("doublerbinary003"," 110 ",4,"$\state{1}$");
tape_output("doublerbinary004"," 1100",4,"$\state{2}$");
tape_output("doublerbinary005"," 1100",3,"$\state{2}$");
tape_output("doublerbinary006"," 1100",2,"$\state{2}$");
tape_output("doublerbinary007"," 1100",1,"$\state{2}$");
tape_output("doublerbinary008"," 1100",0,"$\state{2}$");
tape_output("doublerbinary009"," 1100",1,"$\state{3}$");

