// pdfs/infloop.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("infloop000"," ",0,"$\state{0}$");
tape_output("infloop001"," ",0,"$\state{0}$");
tape_output("infloop002"," ",0,"$\state{0}$");
tape_output("infloop003"," ",0,"$\state{0}$");
tape_output("infloop004"," ",0,"$\state{0}$");
tape_output("infloop005"," ",0,"$\state{0}$");
tape_output("infloop006"," ",0,"$\state{0}$");
tape_output("infloop007"," ",0,"$\state{0}$");
tape_output("infloop008"," ",0,"$\state{0}$");
tape_output("infloop009"," ",0,"$\state{0}$");
tape_output("infloop010"," ",0,"$\state{0}$");

