// pdfs/leq.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("leq000","11 111    ",0,"$\state{0}$");
tape_output("leq001","B1 111    ",0,"$\state{1}$");
tape_output("leq002","B1 111    ",1,"$\state{2}$");
tape_output("leq003","B1B111    ",2,"$\state{2}$");
tape_output("leq004","B1B111    ",3,"$\state{3}$");
tape_output("leq005","B1B111    ",4,"$\state{3}$");
tape_output("leq006","B1B111    ",5,"$\state{3}$");
tape_output("leq007","B1B111B   ",6,"$\state{3}$");
tape_output("leq008","B1B1111   ",6,"$\state{4}$");
tape_output("leq009","B1B1111B  ",7,"$\state{5}$");
tape_output("leq010","B1B11111  ",7,"$\state{6}$");
tape_output("leq011","B1B11111  ",6,"$\state{6}$");
tape_output("leq012","B1B11111  ",5,"$\state{6}$");
tape_output("leq013","B1B11111  ",4,"$\state{6}$");
tape_output("leq014","B1B11111  ",3,"$\state{6}$");
tape_output("leq015","B1B11111  ",2,"$\state{6}$");
tape_output("leq016","B1B11111  ",1,"$\state{7}$");
tape_output("leq017","B1B11111  ",0,"$\state{7}$");
tape_output("leq018","B1B11111  ",1,"$\state{8}$");
tape_output("leq019","B1B11111  ",1,"$\state{0}$");
tape_output("leq020","BBB11111  ",1,"$\state{1}$");
tape_output("leq021","BBB11111  ",2,"$\state{2}$");
tape_output("leq022","BBB11111  ",3,"$\state{3}$");
tape_output("leq023","BBB11111  ",4,"$\state{3}$");
tape_output("leq024","BBB11111  ",5,"$\state{3}$");
tape_output("leq025","BBB11111  ",6,"$\state{3}$");
tape_output("leq026","BBB11111  ",7,"$\state{3}$");
tape_output("leq027","BBB11111B ",8,"$\state{3}$");
tape_output("leq028","BBB111111 ",8,"$\state{4}$");
tape_output("leq029","BBB111111B",9,"$\state{5}$");
tape_output("leq030","BBB1111111",9,"$\state{6}$");
tape_output("leq031","BBB1111111",8,"$\state{6}$");
tape_output("leq032","BBB1111111",7,"$\state{6}$");
tape_output("leq033","BBB1111111",6,"$\state{6}$");
tape_output("leq034","BBB1111111",5,"$\state{6}$");
tape_output("leq035","BBB1111111",4,"$\state{6}$");
tape_output("leq036","BBB1111111",3,"$\state{6}$");
tape_output("leq037","BBB1111111",2,"$\state{6}$");
tape_output("leq038","BBB1111111",1,"$\state{7}$");
tape_output("leq039","BBB1111111",2,"$\state{8}$");
tape_output("leq040","BBB1111111",3,"$\state{9}$");

