// pdfs/mu_ex1four.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("mu_ex1four000"," 1111 ",1,"$\state{0}$");
tape_output("mu_ex1four001"," 1111 ",2,"$\state{0}$");
tape_output("mu_ex1four002"," 1111 ",3,"$\state{0}$");
tape_output("mu_ex1four003"," 1111 ",4,"$\state{0}$");
tape_output("mu_ex1four004"," 1111 ",5,"$\state{0}$");
tape_output("mu_ex1four005"," 11111",5,"$\state{1}$");
tape_output("mu_ex1four006"," 11111",4,"$\state{1}$");
tape_output("mu_ex1four007"," 11111",3,"$\state{1}$");
tape_output("mu_ex1four008"," 11111",2,"$\state{1}$");
tape_output("mu_ex1four009"," 11111",1,"$\state{1}$");
tape_output("mu_ex1four010"," 11111",0,"$\state{1}$");
tape_output("mu_ex1four011"," 11111",1,"$\state{2}$");

