// pdfs/mu_ex3zero.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("mu_ex3zero000","   ",0,"$\state{0}$");
tape_output("mu_ex3zero001","   ",1,"$\state{1}$");
tape_output("mu_ex3zero002","   ",2,"$\state{2}$");
tape_output("mu_ex3zero003","   ",1,"$\state{3}$");
tape_output("mu_ex3zero004","   ",0,"$\state{4}$");

