// pdfs/mu_ex1three.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("mu_ex1three000"," 111 ",1,"$\state{0}$");
tape_output("mu_ex1three001"," 111 ",2,"$\state{0}$");
tape_output("mu_ex1three002"," 111 ",3,"$\state{0}$");
tape_output("mu_ex1three003"," 111 ",4,"$\state{0}$");
tape_output("mu_ex1three004"," 1111",4,"$\state{1}$");
tape_output("mu_ex1three005"," 1111",3,"$\state{1}$");
tape_output("mu_ex1three006"," 1111",2,"$\state{1}$");
tape_output("mu_ex1three007"," 1111",1,"$\state{1}$");
tape_output("mu_ex1three008"," 1111",0,"$\state{1}$");
tape_output("mu_ex1three009"," 1111",1,"$\state{2}$");

