// pdfs/mu_ex1five.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("mu_ex1five000"," 11111 ",1,"$\state{0}$");
tape_output("mu_ex1five001"," 11111 ",2,"$\state{0}$");
tape_output("mu_ex1five002"," 11111 ",3,"$\state{0}$");
tape_output("mu_ex1five003"," 11111 ",4,"$\state{0}$");
tape_output("mu_ex1five004"," 11111 ",5,"$\state{0}$");
tape_output("mu_ex1five005"," 11111 ",6,"$\state{0}$");
tape_output("mu_ex1five006"," 111111",6,"$\state{1}$");
tape_output("mu_ex1five007"," 111111",5,"$\state{1}$");
tape_output("mu_ex1five008"," 111111",4,"$\state{1}$");
tape_output("mu_ex1five009"," 111111",3,"$\state{1}$");
tape_output("mu_ex1five010"," 111111",2,"$\state{1}$");
tape_output("mu_ex1five011"," 111111",1,"$\state{1}$");
tape_output("mu_ex1five012"," 111111",0,"$\state{1}$");
tape_output("mu_ex1five013"," 111111",1,"$\state{2}$");

