// pdfs/mu_ex2four.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("mu_ex2four000"," 1111",1,"$\state{0}$");
tape_output("mu_ex2four001"," 1111",0,"$\state{1}$");
tape_output("mu_ex2four002","11111",0,"$\state{2}$");

