// pdfs/mu_ex3one.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("mu_ex3one000","1  ",0,"$\state{0}$");
tape_output("mu_ex3one001","1  ",1,"$\state{1}$");
tape_output("mu_ex3one002","1  ",2,"$\state{2}$");
tape_output("mu_ex3one003","1  ",1,"$\state{3}$");
tape_output("mu_ex3one004","1  ",0,"$\state{4}$");

