// pdfs/mu_ex1two.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("mu_ex1two000"," 11 ",1,"$\state{0}$");
tape_output("mu_ex1two001"," 11 ",2,"$\state{0}$");
tape_output("mu_ex1two002"," 11 ",3,"$\state{0}$");
tape_output("mu_ex1two003"," 111",3,"$\state{1}$");
tape_output("mu_ex1two004"," 111",2,"$\state{1}$");
tape_output("mu_ex1two005"," 111",1,"$\state{1}$");
tape_output("mu_ex1two006"," 111",0,"$\state{1}$");
tape_output("mu_ex1two007"," 111",1,"$\state{2}$");

