// pdfs/mu_ex1zero.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("mu_ex1zero000","  ",1,"$\state{0}$");
tape_output("mu_ex1zero001"," 1",1,"$\state{1}$");
tape_output("mu_ex1zero002"," 1",0,"$\state{1}$");
tape_output("mu_ex1zero003"," 1",1,"$\state{2}$");

