// pdfs/mystery11.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("mystery11000","11 ",0,"$\state{0}$");
tape_output("mystery11001","11 ",1,"$\state{1}$");
tape_output("mystery11002","11 ",2,"$\state{0}$");
tape_output("mystery11003","11 ",2,"$\state{4}$");

