// pdfs/mystery1101.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("mystery1101000","1101 ",0,"$\state{0}$");
tape_output("mystery1101001","1101 ",1,"$\state{1}$");
tape_output("mystery1101002","1101 ",2,"$\state{0}$");
tape_output("mystery1101003","1101 ",3,"$\state{0}$");
tape_output("mystery1101004","1101 ",4,"$\state{1}$");
tape_output("mystery1101005","1101 ",4,"$\state{4}$");

