// pdfs/odd_four.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("odd_four000","1111 ",0,"$\state{0}$");
tape_output("odd_four001","1111 ",1,"$\state{1}$");
tape_output("odd_four002","1 11 ",1,"$\state{2}$");
tape_output("odd_four003","1 11 ",0,"$\state{3}$");
tape_output("odd_four004","  11 ",0,"$\state{4}$");
tape_output("odd_four005","  11 ",1,"$\state{5}$");
tape_output("odd_four006","  11 ",2,"$\state{0}$");
tape_output("odd_four007","  11 ",3,"$\state{1}$");
tape_output("odd_four008","  1  ",3,"$\state{2}$");
tape_output("odd_four009","  1  ",2,"$\state{3}$");
tape_output("odd_four010","     ",2,"$\state{4}$");
tape_output("odd_four011","     ",3,"$\state{5}$");
tape_output("odd_four012","     ",4,"$\state{0}$");
tape_output("odd_four013","     ",4,"$\state{100}$");

