// pdfs/odd_three.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("odd_three000","111 ",0,"$\state{0}$");
tape_output("odd_three001","111 ",1,"$\state{1}$");
tape_output("odd_three002","1 1 ",1,"$\state{2}$");
tape_output("odd_three003","1 1 ",0,"$\state{3}$");
tape_output("odd_three004","  1 ",0,"$\state{4}$");
tape_output("odd_three005","  1 ",1,"$\state{5}$");
tape_output("odd_three006","  1 ",2,"$\state{0}$");
tape_output("odd_three007","  1 ",3,"$\state{1}$");
tape_output("odd_three008","  1 ",2,"$\state{100}$");

