// pdfs/palindromeabba.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("palindromeabba000","abba ",0,"$\state{0}$");
tape_output("palindromeabba001"," bba ",0,"$\state{1}$");
tape_output("palindromeabba002"," bba ",1,"$\state{2}$");
tape_output("palindromeabba003"," bba ",1,"$\state{20}$");
tape_output("palindromeabba004"," bba ",2,"$\state{20}$");
tape_output("palindromeabba005"," bba ",3,"$\state{20}$");
tape_output("palindromeabba006"," bba ",4,"$\state{20}$");
tape_output("palindromeabba007"," bba ",3,"$\state{21}$");
tape_output("palindromeabba008"," bb  ",3,"$\state{40}$");
tape_output("palindromeabba009"," bb  ",2,"$\state{41}$");
tape_output("palindromeabba010"," bb  ",1,"$\state{41}$");
tape_output("palindromeabba011"," bb  ",0,"$\state{41}$");
tape_output("palindromeabba012"," bb  ",1,"$\state{0}$");
tape_output("palindromeabba013","  b  ",1,"$\state{3}$");
tape_output("palindromeabba014","  b  ",2,"$\state{4}$");
tape_output("palindromeabba015","  b  ",2,"$\state{30}$");
tape_output("palindromeabba016","  b  ",3,"$\state{30}$");
tape_output("palindromeabba017","  b  ",2,"$\state{31}$");
tape_output("palindromeabba018","     ",2,"$\state{40}$");
tape_output("palindromeabba019","     ",1,"$\state{41}$");
tape_output("palindromeabba020","     ",2,"$\state{0}$");
tape_output("palindromeabba021","     ",2,"$\state{80}$");
tape_output("palindromeabba022","  1  ",2,"$\state{100}$");

