// pdfs/palindromeaba.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("palindromeaba000","aba ",0,"$\state{0}$");
tape_output("palindromeaba001"," ba ",0,"$\state{1}$");
tape_output("palindromeaba002"," ba ",1,"$\state{2}$");
tape_output("palindromeaba003"," ba ",1,"$\state{20}$");
tape_output("palindromeaba004"," ba ",2,"$\state{20}$");
tape_output("palindromeaba005"," ba ",3,"$\state{20}$");
tape_output("palindromeaba006"," ba ",2,"$\state{21}$");
tape_output("palindromeaba007"," b  ",2,"$\state{40}$");
tape_output("palindromeaba008"," b  ",1,"$\state{41}$");
tape_output("palindromeaba009"," b  ",0,"$\state{41}$");
tape_output("palindromeaba010"," b  ",1,"$\state{0}$");
tape_output("palindromeaba011","    ",1,"$\state{3}$");
tape_output("palindromeaba012","    ",2,"$\state{4}$");
tape_output("palindromeaba013","    ",1,"$\state{80}$");
tape_output("palindromeaba014"," 1  ",1,"$\state{100}$");

