// pdfs/pred.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("pred000"," 111 ",1,"$\state{0}$");
tape_output("pred001"," 111 ",2,"$\state{0}$");
tape_output("pred002"," 111 ",3,"$\state{0}$");
tape_output("pred003"," 111 ",4,"$\state{0}$");
tape_output("pred004"," 111 ",3,"$\state{1}$");
tape_output("pred005"," 11  ",3,"$\state{1}$");
tape_output("pred006"," 11  ",2,"$\state{2}$");
tape_output("pred007"," 11  ",1,"$\state{2}$");
tape_output("pred008"," 11  ",0,"$\state{2}$");
tape_output("pred009"," 11  ",1,"$\state{3}$");

