// pdfs/pred_empty.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("pred_empty000","   ",2,"$\state{0}$");
tape_output("pred_empty001","   ",1,"$\state{1}$");
tape_output("pred_empty002","   ",0,"$\state{2}$");
tape_output("pred_empty003","   ",1,"$\state{3}$");

