// pdfs/pred_five.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("pred_five000"," 11111 ",1,"$\state{0}$");
tape_output("pred_five001"," 11111 ",2,"$\state{0}$");
tape_output("pred_five002"," 11111 ",3,"$\state{0}$");
tape_output("pred_five003"," 11111 ",4,"$\state{0}$");
tape_output("pred_five004"," 11111 ",5,"$\state{0}$");
tape_output("pred_five005"," 11111 ",6,"$\state{0}$");
tape_output("pred_five006"," 11111 ",5,"$\state{1}$");
tape_output("pred_five007"," 1111  ",5,"$\state{1}$");
tape_output("pred_five008"," 1111  ",4,"$\state{2}$");
tape_output("pred_five009"," 1111  ",3,"$\state{2}$");
tape_output("pred_five010"," 1111  ",2,"$\state{2}$");
tape_output("pred_five011"," 1111  ",1,"$\state{2}$");
tape_output("pred_five012"," 1111  ",0,"$\state{2}$");
tape_output("pred_five013"," 1111  ",1,"$\state{3}$");

