// pdfs/pred_two.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("pred_two000"," 11 ",1,"$\state{0}$");
tape_output("pred_two001"," 11 ",2,"$\state{0}$");
tape_output("pred_two002"," 11 ",3,"$\state{0}$");
tape_output("pred_two003"," 11 ",2,"$\state{1}$");
tape_output("pred_two004"," 1  ",2,"$\state{1}$");
tape_output("pred_two005"," 1  ",1,"$\state{2}$");
tape_output("pred_two006"," 1  ",0,"$\state{2}$");
tape_output("pred_two007"," 1  ",1,"$\state{3}$");

