// pdfs/singlebitand.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("singlebitand000","01",0,"$\state{0}$");
tape_output("singlebitand001"," 1",0,"$\state{10}$");
tape_output("singlebitand002"," 1",1,"$\state{11}$");
tape_output("singlebitand003"," 0",1,"$\state{100}$");

