// pdfs/startswithzeroone.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

string OUTPUT_FN = "pdfs/startswithzeroone%03d";

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("startswithzeroone000","01101 ",0,"$\state{0}$");
tape_output("startswithzeroone001","B1101 ",0,"$\state{1}$");
tape_output("startswithzeroone002","B1101 ",1,"$\state{2}$");
tape_output("startswithzeroone003","B1101 ",2,"$\state{4}$");
tape_output("startswithzeroone004","B1B01 ",2,"$\state{5}$");
tape_output("startswithzeroone005","B1B01 ",3,"$\state{4}$");
tape_output("startswithzeroone006","B1BB1 ",3,"$\state{5}$");
tape_output("startswithzeroone007","B1BB1 ",4,"$\state{4}$");
tape_output("startswithzeroone008","B1BBB ",4,"$\state{5}$");
tape_output("startswithzeroone009","B1BBBB",5,"$\state{4}$");
tape_output("startswithzeroone010","B1BBBB",5,"$\state{6}$");
tape_output("startswithzeroone011","B1BBBB",4,"$\state{6}$");
tape_output("startswithzeroone012","B1BBBB",3,"$\state{6}$");
tape_output("startswithzeroone013","B1BBBB",2,"$\state{6}$");
tape_output("startswithzeroone014","B1BBBB",1,"$\state{6}$");
tape_output("startswithzeroone015","B1BBBB",1,"$\state{10}$");

