// pdfs/startswithzero.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

string OUTPUT_FN = "pdfs/startswithzero%03d";

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("startswithzero000","01101 ",0,"$\state{0}$");
tape_output("startswithzero001","11101 ",0,"$\state{1}$");
tape_output("startswithzero002","11101 ",1,"$\state{2}$");
tape_output("startswithzero003","1B101 ",1,"$\state{3}$");
tape_output("startswithzero004","1B101 ",2,"$\state{2}$");
tape_output("startswithzero005","1BB01 ",2,"$\state{3}$");
tape_output("startswithzero006","1BB01 ",3,"$\state{2}$");
tape_output("startswithzero007","1BBB1 ",3,"$\state{3}$");
tape_output("startswithzero008","1BBB1 ",4,"$\state{2}$");
tape_output("startswithzero009","1BBBB ",4,"$\state{3}$");
tape_output("startswithzero010","1BBBBB",5,"$\state{2}$");
tape_output("startswithzero011","1BBBBB",5,"$\state{4}$");
tape_output("startswithzero012","1BBBBB",4,"$\state{4}$");
tape_output("startswithzero013","1BBBBB",3,"$\state{4}$");
tape_output("startswithzero014","1BBBBB",2,"$\state{4}$");
tape_output("startswithzero015","1BBBBB",1,"$\state{4}$");
tape_output("startswithzero016","1BBBBB",0,"$\state{4}$");
tape_output("startswithzero017","1BBBBB",0,"$\state{10}$");

