// pdfs/startswithzerostarone.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

string OUTPUT_FN = "pdfs/startswithzerostarone%03d";

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("startswithzerostarone000","00110 ",0,"$\state{0}$");
tape_output("startswithzerostarone001","B0110 ",0,"$\state{1}$");
tape_output("startswithzerostarone002","B0110 ",1,"$\state{0}$");
tape_output("startswithzerostarone003","BB110 ",1,"$\state{1}$");
tape_output("startswithzerostarone004","BB110 ",2,"$\state{0}$");
tape_output("startswithzerostarone005","BB110 ",3,"$\state{2}$");
tape_output("startswithzerostarone006","BB1B0 ",3,"$\state{3}$");
tape_output("startswithzerostarone007","BB1B0 ",4,"$\state{2}$");
tape_output("startswithzerostarone008","BB1BB ",4,"$\state{3}$");
tape_output("startswithzerostarone009","BB1BBB",5,"$\state{2}$");
tape_output("startswithzerostarone010","BB1BBB",4,"$\state{4}$");
tape_output("startswithzerostarone011","BB1BBB",3,"$\state{4}$");
tape_output("startswithzerostarone012","BB1BBB",2,"$\state{4}$");
tape_output("startswithzerostarone013","BB1BBB",2,"$\state{10}$");

