// pdfs/successor.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("successor000"," 111",1,"$\state{0}$");
tape_output("successor001"," 111",0,"$\state{0}$");
tape_output("successor002","1111",0,"$\state{1}$");

