// pdfs/twobsabba.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("twobsabba000","abba",0,"$\state{0}$");
tape_output("twobsabba001","abba",1,"$\state{10}$");
tape_output("twobsabba002","abba",2,"$\state{20}$");
tape_output("twobsabba003","abba",2,"$\state{3}$");

