// pdfs/twobsaba.asy
// Draw a succession of tapes for a Turing machine computation
// This is generated by computing/bin/turing_machine/tm_to_asy.py

import settings;
settings.outformat="pdf";
settings.render=0;

string OUTPUT_FN = "pdfs/twobsaba%03d";

// cd needed for relative import 
cd("../../../../asy");
// import jh;
import tape;
cd("");

unitsize(1pt);

tape_output("twobsaba000","aba ",0,"$\state{0}$");
tape_output("twobsaba001","aba ",1,"$\state{10}$");
tape_output("twobsaba002","aba ",2,"$\state{20}$");
tape_output("twobsaba003","aba ",3,"$\state{0}$");
tape_output("twobsaba004","aba ",3,"$\state{4}$");

