// beehive_all.asy
// Running Asymptote on this file will make a graphic or a sequence 
// of graphics {0}000.pdf, {0}001.pdf, etc. for the Game of Life topic
// This file was generated by src/scheme/prologue/life/run_life.py
// on 2025-May-10 14:36 EDT

// Set up defaults
settings.outformat = "pdf";

// Set up LaTeX defaults 
import settexpreamble;
settexpreamble();
// Set up Asy defaults
import jh;

// Get routine one_gameboard(..) that reads a plain text gameboard
import life;

string fn = "beehive";
for (int dex=0; dex<=1; ++dex) {
  picture p = one_gameboard("gameboards",fn,dex,0.25cm);
  shipout(fn+format("%03d",dex), p);
}
